### ISSUE TITLE
Crash when spawning mobs

### ISSUE THREAD

**Issue by uhsting** [ganymedes01/Headcrumbs#35] opened 2015-05-16 08:33 UTC
This is the problem in this issue: https://github.com/CovertJaguar/Railcraft/issues/608#issuecomment-102434750

When I switch to Normal difficulty to spawn mobs, crash occurred. Even if I create a new world, Minecraft crashed again.

The error is correlated to Railcraft. I've tried to see which mod is causing the problem. It seems your mod is not working well with Railcraft, or in order words incompatible.

Error log: http://pastebin.com/4xM1mYvx and http://pastebin.com/XGmicdYa

Please fix, thank you!

P.S. Ran on both Forge versions: 10.13.3.1403 and 10.13.2.1291

**Comment by ganymedes01** [comment] 2015-05-16 12:33
The celebrity entity ID is probably conflicting with the Minecart ID.

My guess is that Railcraft unregisters the vanilla minecart and then register it's own in the same ID. Headcrumbs is probably registers its mob in between those two events, and since the minecart ID is free it automatically takes it.

Try changing that ID in headcrumbs' config file (usually it's an option at the very bottom). Just make sure you use a value between 0 and 128.

**Comment by CovertJaguar** [comment] 2015-05-16 14:22
I'm not really sure how Headcrumbs could register something in the middle of Railcraft's replacement process, unless is some kind of EntityRegisteredEvent or something.

**Comment by ganymedes01** [comment] 2015-05-16 15:08
Well that was just a guess, I'm not really sure what's going on exactly yo be honest.
I use EntityRegistry.findGlobalUniqueEntityId() to find a free id. Any chance that in your replacements the game somehow thinks 44 is free and returns it for me?

**Comment by uhsting** [comment] 2015-05-17 02:59
Maybe I have to take the blame because I've set the ID to 300 when the default ID is crashing as well.

**Comment by uhsting** [comment] 2015-05-17 03:23
No, 44 is already occupied in my modpack.

**Comment by CovertJaguar** [comment] 2015-05-17 07:38
@ganymedes01 I wouldn't think that was possible, but I highly recommend you use EntityRegistry.registerModEntity() and feed it your own locally unique ID set. In other words don't use EntityRegistry.findGlobalUniqueEntityId(), just pick IDs that don't conflict with other entities *you* register in *your mod*. Doing this will prevent you from conflicting with anything ever.

The only thing you lose is easy egg generation, but that's trivially fixed by adding your own egg item.

**Comment by ganymedes01** [comment] 2015-05-17 14:12
Yeah I know of that, I regret using the EntityRegistry.registerGlobalEntityID() method. I saw no warnings about using it so I did. Switching now would cause existing entities to disappear, so that's why I haven't do it yet...

**Comment by CovertJaguar** [comment] 2015-05-17 15:18
@uhsting If you could post the FML Log instead of the crash log, it might shed some light on the root cause.

**Comment by ganymedes01** [comment] 2015-05-17 15:22
He had the ID set to 300...
300 in binary is 100101100
bytes only hold 8 bits, so ignore the first one and you have 00101100... which is 44 in decimal.

**Comment by CovertJaguar** [comment] 2015-05-17 15:23
ah...yep that could do it.

**Comment by CovertJaguar** [comment] 2015-05-17 15:24
I'm surprised that FML lets you do that...

**Comment by ganymedes01** [comment] 2015-05-17 15:29
Same, should probably report it to them

**Closed** 2015-05-17 16:25 UTC

**Comment by ganymedes01** [comment] 2015-05-17 16:29
Reported it here: https://github.com/MinecraftForge/MinecraftForge/issues/1880
