### ISSUE TITLE
Error in position of Statues

### ISSUE THREAD

**Issue by drakray** [ganymedes01/Headcrumbs#66] opened 2016-04-17 02:13 UTC
Picture of error:
http://imgur.com/a/N7Zsi

List of mods:
http://pastebin.com/dhpiaNmJ

**Comment by drakray** [comment] 2016-04-19 17:12
Seems like error come from some weird interaction in my modList, as https://github.com/Nuchaz/BiblioCraft/issues/354

**Comment by buttilda** [comment] 2016-05-07 22:56
Yeah, some mod of yours is messing with how players render... since the problem is also happening to BiblioCraft, I'll put the blame on this mysterious mod and close the issue XD

**Closed as completed by buttilda** 2016-05-07 22:56 UTC
