### ISSUE TITLE
1.12.2 server crashes when anyone joins 

### ISSUE THREAD

**Issue by CommanderBop** [ganymedes01/Headcrumbs#112] opened 2018-10-22 02:16 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3 (2).jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  MalisisCorePlugin (MalisisCore-1.12.2.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.1 (1).jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 10/21/18 10:11 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186332_a(WalkNodeProcessor.java:192)
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186332_a(WalkNodeProcessor.java:219)
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186320_a(WalkNodeProcessor.java:115)
	at net.minecraft.pathfinding.PathFinder.func_186335_a(SourceFile:82)
	at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:40)
	at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30)
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:114)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:51)
	at net.minecraft.pathfinding.PathNavigateGround.func_75494_a(SourceFile:73)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75250_a(EntityAIAttackMelee.java:63)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at com.raz.howlingmoon.entities.EntityWere.func_70636_d(EntityWere.java:363)
	at com.raz.howlingmoon.entities.EntityTameWere.func_70636_d(EntityTameWere.java:166)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.raz.howlingmoon.entities.EntityTameWere.func_70071_h_(EntityTameWere.java:227)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186332_a(WalkNodeProcessor.java:192)
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186332_a(WalkNodeProcessor.java:219)
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186320_a(WalkNodeProcessor.java:115)
	at net.minecraft.pathfinding.PathFinder.func_186335_a(SourceFile:82)
	at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:40)
	at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30)
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:114)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:51)
	at net.minecraft.pathfinding.PathNavigateGround.func_75494_a(SourceFile:73)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75250_a(EntityAIAttackMelee.java:63)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at com.raz.howlingmoon.entities.EntityWere.func_70636_d(EntityWere.java:363)
	at com.raz.howlingmoon.entities.EntityTameWere.func_70636_d(EntityTameWere.java:166)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.raz.howlingmoon.entities.EntityTameWere.func_70071_h_(EntityTameWere.java:227)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: howlingmoon:entitywerewolf (com.raz.howlingmoon.entities.EntityWerewolf)
	Entity ID: 127
	Entity Name: Werewolf
	Entity's Exact location: 41.62, 67.00, 50.54
	Entity's Block location: World: (41,67,50), Chunk: (at 9,4,2 in 2,3; contains blocks 32,0,48 to 47,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [GCEntityPlayerMP['CommanderBopo'/182, l='world', x=-23.50, y=63.00, z=241.50]]
	Chunk stats: ServerChunkCache: 1684 Drop: 0
	Level seed: -8334652099055440007
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-20,64,244), Chunk: (at 12,4,4 in -2,15; contains blocks -32,0,240 to -17,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 722947 game time, 208301 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 17469 (now: false), thunder time: 134613 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8339465568 bytes (7953 MB) / 10300686336 bytes (9823 MB) up to 10300686336 bytes (9823 MB)
	JVM Flags: 2 total; -Xmx10G -Xms10G
	IntCache: cache: 7, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 70 mods loaded, 70 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version          | Source                                              | Signature                                |
	|:--------- |:-------------------- |:---------------- |:--------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2           | minecraft.jar                                       | None                                     |
	| UCHIJAAAA | mcp                  | 9.42             | minecraft.jar                                       | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99        | forge-1.12.2-14.23.5.2768-universal.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.5.2768     | forge-1.12.2-14.23.5.2768-universal.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore        |                  | minecraft.jar                                       | None                                     |
	| UCHIJAAAA | securitycraft        | v1.8.8.1         | [1.12.x]+SecurityCraft+v1.8.8.1.jar                 | None                                     |
	| UCHIJAAAA | jei                  | 4.12.1.217       | jei_1.12.2-4.12.1.217.jar                           | None                                     |
	| UCHIJAAAA | abyssalcraft         | 1.9.4.10         | AbyssalCraft-1.12.2-1.9.4.10 (1).jar                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJAAAA | baubles              | 1.5.2            | Baubles-Mod-1.12.2.jar                              | None                                     |
	| UCHIJAAAA | bettercombatmod      | 1.5.3            | Better-Combat-Rebirth-Mod-1.12.2.jar                | None                                     |
	| UCHIJAAAA | biomesoplenty        | 7.0.1.2399       | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar       | None                                     |
	| UCHIJAAAA | bloodmoon            | 1.5.3            | Bloodmoon-MC1.12.2-1.5.3 (2).jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | buildcraftlib        | 7.99.18          | buildcraft-7.99.18.jar                              | None                                     |
	| UCHIJAAAA | buildcraftcore       | 7.99.18          | buildcraft-7.99.18.jar                              | None                                     |
	| UCHIJAAAA | buildcraftbuilders   | 7.99.18          | buildcraft-7.99.18.jar                              | None                                     |
	| UCHIJAAAA | buildcraftenergy     | 7.99.18          | buildcraft-7.99.18.jar                              | None                                     |
	| UCHIJAAAA | buildcraftfactory    | 7.99.18          | buildcraft-7.99.18.jar                              | None                                     |
	| UCHIJAAAA | buildcraftrobotics   | 7.99.18          | buildcraft-7.99.18.jar                              | None                                     |
	| UCHIJAAAA | buildcrafttransport  | 7.99.18          | buildcraft-7.99.18.jar                              | None                                     |
	| UCHIJAAAA | buildcraftsilicon    | 7.99.18          | buildcraft-7.99.18.jar                              | None                                     |
	| UCHIJAAAA | ichunutil            | 7.1.4            | iChun-Util-Mod-1.12.2 (1).jar                       | None                                     |
	| UCHIJAAAA | clef                 | 7.0.0            | Clef-1.12.2-7.0.0 (2).jar                           | None                                     |
	| UCHIJAAAA | codechickenlib       | 3.2.2.353        | CodeChickenLib-1.12.2-3.2.2.353-universal (1).jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux         | 2.1.0            | RedstoneFlux-1.12-2.1.0.6-universal (2).jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | cofhcore             | 4.6.1            | CoFHCore-1.12.2-4.6.1.22-universal (2).jar          | None                                     |
	| UCHIJAAAA | cofhworld            | 1.3.0            | CoFHWorld-1.12.2-1.3.0.6-universal (2).jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | crafttweaker         | 4.1.11           | CraftTweaker2-1.12-4.1.11.jar                       | None                                     |
	| UCHIJAAAA | crafttweakerjei      | 2.0.2            | CraftTweaker2-1.12-4.1.11.jar                       | None                                     |
	| UCHIJAAAA | dimdoors             | 3.0.0-beta4      | Dimensional-Doors-Mod-1.12.2 (1).jar                | None                                     |
	| UCHIJAAAA | trzlib               | 2.1.8            | TRZLib-1.12.2 (1).jar                               | None                                     |
	| UCHIJAAAA | dimensionalpocketsii | 1.2.10-beta      | Dimensional-Pockets-2-Mod-1.12.2 (2).jar            | None                                     |
	| UCHIJAAAA | fencejumper          | 1.0.5            | fencejumper-1.12-1.0.5.jar                          | None                                     |
	| UCHIJAAAA | ic2                  | 2.8.100-ex112    | Industrial-Craft-2-Mod-Experimental-1.12.2.jar      | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | mantle               | 1.12-1.3.2.24    | Mantle-1.12-1.3.2.24 (1).jar                        | None                                     |
	| UCHIJAAAA | tconstruct           | 1.12.2-2.10.1.87 | TConstruct-1.12.2-2.10.1.87.jar                     | None                                     |
	| UCHIJAAAA | galacticraftcore     | 4.0.1.181        | GalacticraftCore-1.12.2-4.0.1.181.jar               | None                                     |
	| UCHIJAAAA | galacticraftplanets  | 4.0.1.181        | Galacticraft-Planets-1.12.2-4.0.1.181.jar           | None                                     |
	| UCHIJAAAA | grapplemod           | 1.12.2-v10       | grapplemod-v10-1.12.2.jar                           | None                                     |
	| UCHIJAAAA | speedsterheroes      | 1.12.2-2.0.9     | SpeedsterHeroes-1.12.2-2.0.9.jar                    | None                                     |
	| UCHIJAAAA | lucraftcore          | 1.12.2-2.3.1     | LucraftCore-1.12.2-2.3.1 (1).jar                    | None                                     |
	| UCHIJAAAA | heroesexpansion      | 1.12.2-1.2.0     | HeroesExpansion-1.12.2-1.2.0 (1).jar                | None                                     |
	| UCHIJAAAA | howlingmoon          | 0.9              | Howling-Moon-Mod-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | instantunify         | 1.1.2            | instantunify-1.12.2-1.1.2.jar                       | None                                     |
	| UCHIJAAAA | inventorysorter      | 1.13.3+57        | inventorysorter-1.12.2-1.13.3+57.jar                | None                                     |
	| UCHIJAAAA | journeymap           | 1.12.2-5.5.2     | JourneyMap-1.12.2 (2).jar                           | None                                     |
	| UCHIJAAAA | malisiscore          | 1.12.2-6.4.0     | MalisisCore-1.12.2.jar                              | None                                     |
	| UCHIJAAAA | malisisdoors         | 1.12.2-7.3.0     | MalisisDoors-Mod-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | megaloot             | 0.2.30           | megaloot.jar                                        | None                                     |
	| UCHIJAAAA | cfm                  | 5.1.0            | MrCrayfishs-Furniture-Mod-1.12.2.jar                | None                                     |
	| UCHIJAAAA | nofov                | 1.0.1            | NoFov-MC1.12-1.0.1.jar                              | None                                     |
	| UCHIJAAAA | coroutil             | 1.12.1-1.2.13    | NormalMod2.jar                                      | None                                     |
	| UCHIJAAAA | weather2             | 1.12.1-2.6.12    | NormalMod.jar                                       | None                                     |
	| UCHIJAAAA | extendedrenderer     | v1.0             | NormalMod2.jar                                      | None                                     |
	| UCHIJAAAA | configmod            | v1.0             | NormalMod2.jar                                      | None                                     |
	| UCHIJAAAA | roguelike            | 1.8.0            | RoguelikeDungeons-1.12.2-1.8.0 (1).jar              | None                                     |
	| UCHIJAAAA | stg                  | 1.12.2-1.2.3     | stg-1.12.2-1.2.3 (1).jar                            | None                                     |
	| UCHIJAAAA | thaumcraft           | 6.1.BETA26       | Thaumcraft-1.12.2-6.1.BETA26 (1).jar                | None                                     |
	| UCHIJAAAA | thermalfoundation    | 2.6.1            | ThermalFoundation-1.12.2-2.6.1.22-universal (1).jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalexpansion     | 5.5.2            | ThermalExpansion-1.12.2-5.5.2.39-universal (1).jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalcultivation   | 0.3.1            | ThermalCultivation-1.12.2-0.3.1.8-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermaldynamics      | 2.5.3            | ThermalDynamics-1.12.2-2.5.3.16-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalinnovation    | 0.3.1            | ThermalInnovation-1.12.2-0.3.1.8-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | bspkrscore           | at_0.9           | TreeCapitator-Mod-1.12.jar                          | None                                     |
	| UCHIJAAAA | treecapitator        | at_0.9           | TreeCapitator-Mod-1.12.jar                          | None                                     |
	| UCHIJAAAA | vampirism            | 1.3.7            | Vampirism-Mod-1.12.2 (2).jar                        | None                                     |
	| UCHIJAAAA | teamlapen-lib        | 1.3.7            | Vampirism-Mod-1.12.2 (2).jar                        | None                                     |
	| UCHIJAAAA | wanionlib            | 1.12.2-1.5       | WanionLib-1.12.2-1.5.jar                            | None                                     |
	| UCHIJAAAA | zeiyocraft           | 0.8.4            | ZeiyoCraft-Mod-1.12.2.jar                           | None                                     |
	| UCHIJAAAA | immersiveengineering | 0.12-86          | ImmersiveEngineering-0.12-86.jar                    | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | unidict              | 1.12.2-2.9.1     | UniDict-1.12.2-2.9.1.jar                            | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3 (2).jar)
  lumien.bloodmoon.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MalisisCorePlugin (MalisisCore-1.12.2.jar)
  
LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.1 (1).jar)
  lucraft.mods.lucraftcore.core.LCTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 7; [GCEntityPlayerMP['CommanderBopo'/182, l='world', x=-23.50, y=63.00, z=241.50]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by TheTurkeyDev** [comment] 2018-10-22 14:15
Duplicate of #113

**Closed as completed by TheTurkeyDev** 2018-10-22 14:15 UTC
Labels: Duplicate
